version: '3.8'

services:

  api:
    image: python
    restart: unless-stopped
    container_name: api-beers
    build: ./api
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: mysql
    restart: unless-stopped
    container_name: db-beers
    build: ./sql/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "beer"

volumes:
  db: